intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{asserts}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base"

# Export options.
#
lib{asserts}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base"
  cxx.export.libs = $intf_libs
}

# Install into the asserts/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
}
